### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by Lakshmananan** [Lakshmananan/motolinx-rental#2] opened 2020-06-24 04:11 UTC
Need content for the website.

1. Terms and condition
2. About us
3. Contact
4. Testimonials
5. Main page filler

You get the point.
Probably a good idea to get this going one booqable is verified and gucci

**Comment by moeraza** [comment] 2020-06-24 18:57
Terms & Conditions:

TERMS AND CONDITONS





1:48
MOTOLINX RENTALS INC. WATERCRAFT RENTAL AGREEMENT
This watercraft rental agreement is made by and between Motolinx Rentals Inc. and the renter identified below and is effective as of the date of acceptance by checking the box at checkout by the Renter. From here on, Motolinx Rentals Inc and company staff will be referred to as Motolinx. 
CANCELLATION POLICY
IF CANCELLATION IS MADE 3 DAYS BEFORE RENTAL START TIME THEN 100% OF YOUR SECURITY DEPOSIT IS REFUNDABLE AND ONLY 50% OF YOUR RENTAL COST BOOKING CHARGE IS REFUNDABLE. 
IF CANCELLATION IS MADE 2 DAYS BEFORE RENTAL START TIME THEN 100% OF YOUR SECURITY DEPOSIT IS REFUNDABLE AND ONLY 50% OF YOUR RENTAL COST BOOKING CHARGE IS REFUNDABLE. 
IF CANCELLATION IS MADE WITHIN 2 DAYS OF RENTAL START TIME OR RENTER DOES NOT SHOW UP THEN SECURITY DEPOSIT IS 100% REFUNDABLE AND NONE OF YOUR RENTAL CHARGE IS REFUNDABLE. 
LATE RETURN POLICY
IF RENTER RETURNS THE JET SKI LATE THE TIME DURATION WILL BE ROUNDED TO THE NEXT WHOLE HOUR. RENTER WILL BE CHARGED ACCORDING TO THE FOLLOWING PRICING SCHEDULE:
LESS THAN 15 MINUTES LATE: NO CHARGE
MORE THAN 15 MINUTES LATE: 159.99/HOUR
FUEL POLICY: FULL TO FULL. RENTER IS RESPONSIBLE TO REPLACE ANY FUEL USED DURING THEIR USE AND SHALL RETURN THE SKI WITH A FULL TANK. $50 REFUELLING SURCHARGE IS APPLIED IF THE JET SKI IS RETURNED LESS THAN FULL.
RULES FOR USE OF JET SKI AND OTHER EQUIPMENT
Renter agrees that he or she shall use the Jet Ski, including all its equipment, safety (life) vests, motor, gas tank, and optional accessories (hereinafter collectively referred to as "the Jet Ski") only for the purpose of personal boating within the province of Ontario with safety always in mind, and in accordance with ALL of the following rules: (A) Renter shall not consume, nor be under the influence of, any intoxicant (including but not limited to alcohol & cannabis) while operating the Jet Ski. (B) Renter shall follow all posted speed limits and rules of navigation while on the water, and shall stay clear of all other boats on the water. Renter shall not attempt to board another vessel from the Jet Ski or tie off to another boat. Renter shall take care not to allow the Jet Ski to collide or damage other vessels or docks. (C) Renter shall not allow anyone other than the above named Renter to use or operate the Jet Ski other than those who have signed the Boat Rental Safety Checklist and have been explicitly authorized by Motolinx. If Renter fails to disclose other operators, passengers, or users of said equipment, he/she will be personally liable for any damages to the undisclosed individuals, even if such damages arise out of the negligence of Motolinx Rentals. 
RESPONSIBILITY / DAMAGES
Renter shall return the Jet Ski, in good working order and condition, at the end of the rental. If any equipment has been lost or damaged, Renter shall inform Motolinx staff upon return. Renter shall be financially responsible for all lost or damaged equipment or damage to the Jet Ski. Motolinx will charge the Renter for lost or damaged equipment to the credit card on file according to the following schedule of charges:
   Impeller $1,000.00 
 Ratchet Strap $ 60.00
 Glove box cover $80.00 
 Damaged Seat $800/seat 
 Cracked hull $2,500
     Oil cover $60.00
 Life Jacket $ 60.00 
 Lost Key $250
 Totaled Jet Ski $12,500
 BRP Speaker $1000
     Battery cover $100.00 
 Fire Extinguisher $ 180.00
 Lic./Reg./Ins. $100.00
 Front/Rear bumper $300.00
 GoProMax $750.00
This list of charges is not exhaustive and not a waiver of responsibility for other damage to the Jet Ski and Renter shall be fully financially responsible to Motolinx for damages incurred to the Jet ski, trailer or any optional accessories included in the rental. There is a $45 handling fee for processing any damages or lost items. If Jet Ski is returned in an un-rentable condition, Renter agrees to pay Motolinx additional rent of $100/day until Jet Ski is able to be repaired to a rentable condition, with a maximum rental charge of $12,500. 
ACKNOWLEDGMENTS AND AGREEMENTS
By executing this Jet Ski Rental Agreement, Renter acknowledges and agrees: 
(A) Although Renter may receive general instructions on these forms and from Motolinx staff prior to rental, I acknowledge that the instructions received do not qualify as watercraft operation training or safety training. The staff are human and the amount of information that can be provided prior to rental is limited. There is no amount of instruction which can prepare an individual for all of the foreseeable risks associated with operation of watercraft. There is also no substitute for common sense. Renter acknowledges these limitations and agrees to assume all risks associated with operation of the Jet Ski. (B) Renter acknowledges and agrees that he or she has the requisite skills, physical and mental abilities necessary for the proper and safe use of the Jet Ski and swimming skills as may be needed in an emergency. (C) Renter is personally liable for any injury or damage caused to others or their property while operating the Jet Ski, regardless of whether in Renter's party or third parties. (D) Renter agrees to wear a properly fitted and fastened Canadian Coast Guard approved personal floatation device (life jacket) while aboard the Jet Ski or on or in the water and require the same of any passenger. (E) Renter shall not sell or assign this Agreement or sublet the Jet Ski or any part thereof, and at all times during the rental period, the person listed as the Renter shall be the only person operating the Jet Ski (with the exception of additional authorized operators who have completed a proof of competency form). (F) Motolinx provides the Jet Ski without warranty and any guarantees. Motolinx does not maintain or provide emergency personnel or watercraft for rescue or recovery. (G) Motolinx is not liable for the loss or damage to the personal property of the Renter. (H) All watercrafts are fitted with telematic devices. These devices relay real-time information of the watercraft such as velocity and geolocation. Operating the watercraft in an aggressive manner will not only increase your risks for injury but will directly result in excessive wear and tear on components that make up the engine. If at any point our systems indicate continuous aggressive manoeuvre or abuse to the watercraft in any way, your agreement would be terminated effective immediately and the watercraft would need to be returned and would be subject to a mechanical inspection. You will not be refunded any portion of your rental cost. Any components that may need to be replaced will be billed directly to the credit card on file or may be deducted from your deposit. (I) Jet Skis are not permitted to be beached at any point during your rental period. Beaching the watercraft may appear to be a harmless act however as the watercraft approaches shallow terrain the jet sucks in rocks which can damage the impeller and the surrounding components. If this occurs, do not continue to operate the watercraft as it will cause further damage. Immediately remove the lanyard or key and proceed to get the watercraft towed back to the launch site.
WARNINGS
There are significant elements of risk in any adventure sport or activity on the water or associated with the use or presence of water craft, including but not limited to Jet Skis and their related use. These risks are inherent in boating and may be present even if the Jet Ski is used properly and even in still water. The Renter understands and acknowledges that the operation of the Jet Ski involve risks such as, but not limited to: (a) changing water flow, conditions or currents; (b) collision with other participants, any portion of the interior of the craft, other watercraft, manmade or natural objects, including overhanging, submerged and/or semi-submerged trees, branches, rocks and boulders; (c) cold weather and heat related injuries and illnesses including hyperthermia, frostbite, heat exhaustion, sun stroke, and dehydration; (d) inclement weather, variances and extremes of wind, weather and temperature, lightning and the presence of insects and animals; (e) sense of balance, physical coordination, ability to swim, and/or ability to follow directions; (f) loss of control of the craft, collision, capsizing, and sinking of the craft which can result in wetness, injury, exposure to the elements, hypothermia and drowning; (g) injury while getting in and out of the craft; (h) travel, including hiking, portaging and travel to and from the related and unrelated activities; (i) the presence of wild animals, including marine life forms, (j) unavailability of emergency aid services and emergency medical care. The listing of these risks is not intended, and shall not be construed as, all of the possible risks associated with the use of the Jet Ski. 
ASSUMPTION OF RISK
Based upon the warnings above and Renter's acknowledgement of the inherent risks of using and operating a Jet Ski, and that some or all of those risks may be unavoidable even with reasonable care in the use and operation of the Jet Ski, by executing this agreement Renter expressly assumes all risks that arise from the use and operation of the Jet Ski, including the risk of property damage, bodily injury and possibly death, including the acts of others, the unavailability of emergency care and any other foreseeable or unforeseeable factors or circumstances related to the use of the Jet Ski.
WAIVER AND RELEASE OF LIABILITY
The Renter, based upon the warnings and understanding of risks, and predicated in part upon the acknowledgements and assumption of risks described above, does hereby waive, release and discharge Motolinx, its officers, agents, employees, successors and assigns, from any and all claims or liability arising from the use or operation of the Jet Ski, or use of the property, facilities, services or activities organized or sponsored by Motolinx. and agrees that it shall not sue them on account or in connection with any claims, causes of action, injuries, damage, cost of expenses arising therefrom, whether arising from negligence or strict liability, and regardless of the participation of any other third party in the causation of any such injuries, damages, or liability, but excluding claims which arise from gross negligence or willful misconduct on the part of Motolinx Renter acknowledges that this waiver and release includes the waiver of future, unknown claims. 
INDEMNITY
The Renter agrees to indemnify and defend, Motolinx and its officers, employees and agents (each, an "Indemnitee") and hold them harmless from any or all claims, causes of action, damage judgments, costs or expenses, including attorney fees which in any way arise from the Renter's use or operation of the Jet Ski, which include but are not limited to damages to or destruction of any property of an Indemnitee, of any others, injury or death of the renter or anyone else or any liability arising from the negligent acts or omissions of an Indemnitee, the renter or anyone else; provided, however, the foregoing indemnity shall not apply to claims related solely to the gross negligence or willful misconduct of Motolinx. The renter agrees to pay for any or all damages to any property of Indemnitee caused by the renter either negligently, willfully, or otherwise. 
In Witness Whereof, the Renter has read, understands and agrees to be legally bound to this Jet Ski Rental Agreement-Waiver and Release of Liability, realizes it relates to surrendering valuable legal rights and assuming important legal responsibilities, does so freely and voluntarily, and does so for himself or herself and his or her heirs, assigns and legal representatives.

**Closed** 2020-06-29 13:42 UTC
Labels: enhancement
